blank_issues_enabled: true
contact_links:
  - name: COINWOW Core Security Policy
    url: https://github.com/COINWOW/COINWOW/security/policy
    about: View security policy
  - name: COINWOW website
    url: https://coinwow.ca
    about: COINWOW homepage
