#ifndef COINWOW_CHAINPARAMSSEEDS_H
#define COINWOW_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the coinwow network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xb2,0x68,0x5b,0xfc,0xc8,0xf5,
    0x01,0x04,0x94,0x71,0xab,0x2e,0xc8,0xf5,
    0x01,0x04,0xb2,0x68,0x0c,0xe1,0xc8,0xf5,
    0x01,0x04,0x36,0x26,0xb7,0x6c,0xc8,0xf5,
};

// chainparams_seed_signet: no fixed seeds

// chainparams_seed_test: no fixed seeds

// chainparams_seed_testnet4: no fixed seeds
#endif // COINWOW_CHAINPARAMSSEEDS_H
